version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-lts-latest
  tools:
    python: '3.12'
  jobs:
    # See https://github.com/readthedocs/readthedocs.org/issues/4912
    # pre_create_environment:
    #   - asdf plugin add poetry
    #   - asdf install poetry latest
    #   - asdf global poetry latest
    #   - poetry config virtualenvs.create false
    pre_install:
      - python -m pip install --upgrade --no-cache-dir pip setuptools sphinx
      - $READTHEDOCS_VIRTUALENV_PATH/bin/python -m pip install --no-cache-dir poetry
      - $READTHEDOCS_VIRTUALENV_PATH/bin/poetry install --only main --only docs

sphinx:
  configuration: 'docs/conf.py'
  fail_on_warning: true
