[tool.poetry]
name = "pacwrap"
description = "Provides single interface to several common Linux package managers."
version = "0.3.0"
license = "MIT"

authors = ["Quien Sabe <qs5779@mail.com>"]

readme = "README.md"

homepage = "https://github.com/wtfo-guru/pacwrap"
documentation = "https://python-pacwrap.readthedocs.io/en/stable"

keywords = []

classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: System Administrators",
  "Operating System :: POSIX :: Linux",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Utilities",
  "Typing :: Typed",
]

[tool.poetry.scripts]
pacwrap = "pacwrap.cli:main"

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.1.0"
distro = "^1.8.0"
wheel = "^0.38"
wtforglib = "^0.3.0"
cmp-version = "^3.0.0"

[tool.poetry.group.test.dependencies]
mypy = "^0.982"
wemake-python-styleguide = "^0.17"
flake8-pytest-style = "^1.6"
doc8 = "^1.0"
nitpick = "^0.32"
# safety = "^2.3"
pytest = "^7.1"
pytest-cov = "^4.0"
pytest-randomly = "^3.12"
bump2version = "^1.0.1"
isort = "^5.11.2"
black = "^22.12.0"
setuptools = "^65.6.3"
importlib-resources = "^5.10.1"
importlib-metadata = { version = "<5.0", python = "<3.8" }

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^5.2"
sphinx-autodoc-typehints = "^1.19"
m2r2 = "^0.3"
tomli = "^2.0"


[tool.poetry.group.dev.dependencies]
packaging = "^22.0"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style-wemake.toml"
