[tool.poetry]
name = "pacwrap"
description = "Provides single interface to several common Linux package managers."
version = "0.3.0-dev0"
license = "MIT"

authors = ["Quien Sabe <qs5779@mail.com>"]

readme = "README.md"

repository = "https://github.com/wtfo-guru/pacwrap"

keywords = []

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.scripts]
pacwrap = "pacwrap.cli:main"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.0"
distro = "^1.8.0"
packaging = "^22.0"
wheel = "^0.38"
wtforglib = {git = "https://github.com/wtfo-guru/wtforglib.git", rev = "v0.2.1"}

[tool.poetry.group.test.dependencies]
mypy = "^0.982"

wemake-python-styleguide = "^0.17"
flake8-pytest-style = "^1.6"
doc8 = "^1.0"
nitpick = "^0.32"

safety = "^2.3"

pytest = "^7.1"
pytest-cov = "^4.0"
pytest-randomly = "^3.12"
bump2version = "^1.0.1"
isort = "^5.11.2"
black = "^22.12.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^5.2"
sphinx-autodoc-typehints = "^1.19"
m2r2 = "^0.3"
tomli = "^2.0"


[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"


[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style-wemake.toml"
