---
version: 2.1

jobs:
  test:
    docker:
      - image: ghcr.io/qs5779/python-multi:edge
    steps:
      - checkout
      - run:
          name: Test
          command: tox

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: main
...
